import type { SiteDict } from "./types";

export const en: SiteDict = {
  lang: "en",
  meta: {
    title: "TeacherAid: every class starts with a question",
    description:
      "A lesson system for secondary schools in North Macedonia. The teacher prepares the lesson in five minutes, students answer on their own phones, the headmaster gets a monthly report.",
    ogAlt: "TeacherAid. Every class starts with a question.",
  },
  nav: {
    home: "TeacherAid, home",
    links: [
      { href: "#class", label: "The lesson" },
      { href: "#why", label: "Why" },
      { href: "#teacher", label: "Teacher" },
      { href: "#report", label: "Headmaster" },
      { href: "#privacy", label: "Data" },
    ],
    cta: "Book a lesson",
    menu: "Menu",
    close: "Close",
    skip: "Skip to content",
    switchLabel: "Прочитајте на македонски",
    switchShort: "МК",
    switchHref: "/",
  },
  hero: {
    title: "Every class starts with a question.",
    deck: "TeacherAid builds the 45-minute lesson around one question. The teacher prepares it in five minutes, students answer on their own phones, and the headmaster gets a one-page report every month.",
    cta: "Book a free lesson",
    secondary: "See one lesson",
    anchor: "45",
    anchorLabel: "minutes, from the QR code to the review",
    meta: ["Secondary schools in North Macedonia", "Teacher · student · headmaster", "Built in Macedonian", "Bitola, 2026"],
    chips: {
      joined: "Joined",
      joinedCount: "24 of 29",
      reason: "+8 for a reason, right or wrong",
      focus: "Focus lock is on",
    },
    phoneAlt: "A student's phone: an opener question about light bulbs with a 24-second timer.",
  },
  problem: {
    index: "i",
    kicker: "08:00, Tuesday",
    lines: [
      "The teacher talks.",
      "Thirty heads look down.",
      "Attention drops within the first few minutes.",
      "And there is already a phone on every desk.",
    ],
    answer: "What if the first thing on that phone was a question about today's lesson?",
    note: "Attention in lectures drops within minutes and recovers during active tasks. Bunce, Flens and Neiles, 2010.",
  },
  lesson: {
    index: "ii",
    kicker: "The lesson, minute by minute",
    title: "One lesson. Forty-five minutes.",
    minute: "min",
    stepsLabel: "Minutes of the lesson",
    steps: [
      {
        minute: 0,
        screen: "join",
        icon: "scan",
        title: "Scan.",
        body: "The teacher puts the code on the board. One scan and the student is in. Attendance is done without a roll call.",
        alt: "The screen for scanning the code on the board.",
      },
      {
        minute: 1,
        screen: "lobby",
        icon: "shield",
        title: "Focus lock.",
        body: "For the length of the lesson, social media, games and messaging are paused. The teacher sees only whether the student is in TeacherAid.",
        alt: "The 'you're in' screen with focus lock on.",
      },
      {
        minute: 2,
        screen: "vote",
        icon: "bulb",
        title: "Opener: predict.",
        body: "A question about today's topic, before it is taught. Every student votes.",
        alt: "An opener with four possible answers and a timer.",
      },
      {
        minute: 4,
        screen: "reason",
        icon: "chat",
        title: "Why? One sentence.",
        body: "The student explains the choice. A reason earns points, right or wrong.",
        alt: "A one-sentence reason field.",
      },
      {
        minute: 5,
        screen: "result",
        icon: "target",
        title: "Not quite. +8.",
        body: "A wrong answer with a reason is worth almost as much as a right one. The teacher reads a few reasons aloud, without names.",
        ice: true,
        alt: "The result on the ice background: not quite, plus eight points.",
      },
      {
        minute: 22,
        screen: "question",
        icon: "bolt",
        title: "A live question.",
        body: "The teacher teaches as usual. Whenever they want, one tap sends a question to every phone, with a timer.",
        alt: "Question 5 of 7 with an 18-second timer.",
      },
      {
        minute: 23,
        screen: "correct",
        icon: "check",
        title: "Correct. +13.",
        body: "Ten points for the right answer and a bonus for speed. Wrong answers are collected for the end of the lesson.",
        alt: "Correct: plus ten points and plus three for speed.",
      },
      {
        minute: 31,
        screen: "ask",
        icon: "private",
        title: "Ask the teacher.",
        body: "The question nobody would ask out loud. Classmates never see who asked. The teacher does.",
        alt: "A question to the teacher, visible only to the teacher.",
      },
      {
        minute: 45,
        screen: "progress",
        icon: "progress",
        title: "Review.",
        body: "The last five minutes: the questions the class got wrong most, and the students' own questions. Absences are ready for e-Дневник.",
        alt: "The student's progress by topic.",
      },
    ],
  },
  why: {
    index: "iii",
    kicker: "Why it works",
    title: "Guess first. Then learn.",
    body: "When students predict before the lesson, they remember what follows better, even when the prediction is wrong. That is why a wrong answer with a reason scores almost as much as a right one.",
    points: [
      { value: "+10", label: "right answer" },
      { value: "+8", label: "a reason, right or wrong" },
    ],
    research: [
      {
        name: "Productive failure",
        finding: "Students who try first and fail learn the lesson that follows more deeply.",
        cite: "Kapur, 2008 · Sinha and Kapur, 2021, 53 studies",
      },
      {
        name: "The pretesting effect",
        finding: "A question before learning, even a failed one, improves later recall.",
        cite: "Kornell, Hays and Bjork, 2009 · Richland, Kornell and Kao, 2009",
      },
      {
        name: "Hypercorrection",
        finding: "Errors made with confidence are the easiest to correct. That is why we ask for one sentence.",
        cite: "Butterfield and Metcalfe, 2001 · Metcalfe, 2017",
      },
    ],
  },
  teacher: {
    index: "iv",
    kicker: "For the teacher",
    title: "Five minutes before the lesson.",
    body: "Pick the subject and the topic, and add one sentence about what matters today. TeacherAid prepares the whole lesson in Macedonian, and you edit whatever you like.",
    inputLabel: "You enter",
    input: {
      subject: "Physics · Year 2",
      topic: "Series and parallel circuits",
      focus: "Understand why the bulb's brightness changes.",
    },
    outputLabel: "You get",
    opener: {
      label: "Opener · Prediction",
      text: "What happens to the bulb's brightness if we add a second identical bulb in series?",
    },
    outputs: [
      { title: "7 live questions", body: "With correct answers and a short explanation for each." },
      { title: "A timer for each question", body: "Shorter for recall, longer for a calculation." },
      { title: "A review summary", body: "What to go over in the last five minutes." },
    ],
    refineLabel: "One tap to change it",
    refinements: ["Easier", "Harder", "More questions", "Make the opener a debate", "Shorter timers"],
    note: "The lesson stays saved. Run it again next year, and colleagues at your school can make their own copy.",
    typesLabel: "Question types",
    types: ["Multiple choice", "True / false", "Numeric", "One-line reason"],
    phoneAlt: "A numeric question: current in amperes, answer 0.6.",
  },
  report: {
    index: "v",
    kicker: "For the headmaster",
    title: "Does nothing. Gets everything.",
    body: "Once a month, one page in your inbox. No login, no setup, no training. Written so you can forward it straight to parents, the municipality or the local press.",
    sample: {
      brand: "TeacherAid",
      month: "Monthly report · October 2026",
      tag: "Sample",
      figures: [
        { value: "286", label: "lessons run" },
        { value: "41", unit: "of 52", label: "active teachers" },
        { value: "93.4", unit: "%", label: "average attendance" },
        { value: "91", unit: "%", label: "of students answer" },
      ],
      classesLabel: "Most active classes",
      classes: "II-3 · III-1 · IV-2",
      summaryLabel: "In short",
      summary:
        "In October, teachers ran 286 lessons with TeacherAid. Attendance is steady and participation is rising in all four years.",
      trend: "↑ 18 more lessons than September",
      older: ["September 2026"],
    },
    notes: [
      "Page one is for forwarding.",
      "Page two is for you only: how you compare with other schools.",
      "A permanent private link to every past report.",
    ],
    disclaimer: "Sample. The figures are illustrative.",
  },
  trust: {
    index: "vi",
    kicker: "The phone and the data",
    title: "The phone, finally, on the lesson's side.",
    focus: "During the lesson, TeacherAid pauses social media, games and messaging. It never reads what a student does in other apps. It only knows whether TeacherAid is open.",
    policy: "The teacher decides when phones are used in class. That is how the Minister of Education described the practice in May 2026.",
    policySource: "Republika.mk, 11 May 2026",
    offlineTitle: "Weak signal?",
    offlineBody:
      "The answer is kept on the phone and sent as soon as the network is back, with the time it was given. The teacher can tell who is offline and who has not answered.",
    phoneAlt: "The offline screen: the answer is saved and will count.",
    items: [
      {
        icon: "shield",
        title: "The school owns the data.",
        body: "We process it only under an agreement with each school, under the Macedonian data protection law (ЗЗЛП). When a student leaves, their data is deleted within 30 days of the school's request.",
      },
      {
        icon: "cloud",
        title: "Hosted in the EU.",
        body: "Encrypted in transit and at rest. Each teacher sees only their own classes.",
      },
      {
        icon: "private",
        title: "Names never reach the AI.",
        body: "Lessons are generated from the topic and the teacher's sentence, never from the class list.",
      },
      {
        icon: "check",
        title: "Only what the lesson needs.",
        body: "Attendance, answers and points. No grades, no location, no contacts, nothing from other apps.",
      },
      {
        icon: "lock",
        title: "No standing access for our team.",
        body: "Access only through a support request, time-limited and visible to the school.",
      },
      {
        icon: "progress",
        title: "TeacherAid does not grade.",
        body: "The teacher sees the points and answers and decides whether and how they count.",
      },
    ],
  },
  country: {
    index: "vii",
    kicker: "North Macedonia",
    figures: [
      { value: 128, label: "secondary schools" },
      { value: 67143, label: "students" },
      { value: 7000, prefix: "about", label: "teachers" },
    ],
    tail: "One national curriculum. One language. Forty-five-minute periods.",
    closing: "Every school in the country can start with a question. We begin with a pilot in the 2026/27 school year.",
    source: "State Statistical Office, start of the 2024/25 school year. The teacher count is an estimate.",
  },
  contact: {
    index: "viii",
    kicker: "A free lesson",
    title: "Book a free lesson at your school.",
    body: "Two of us come to your school and run a real lesson with one class: the opener, live questions and the review. You and your teachers watch.",
    cta: "Book a free lesson",
    email: "hello@teacheraid.education",
    subject: "A free TeacherAid lesson at our school",
    mailBody: "Hello,\n\nWe would like to book a free lesson with TeacherAid.\n\nSchool:\nCity:\nPhone:\n",
    copy: "Copy address",
    copied: "Copied",
    pilot: "For the 2026/27 school year we are looking for our first pilot schools.",
  },
  footer: {
    line: "Every class starts with a question.",
    made: "Started at Startup Weekend Bitola, September 2026.",
    rights: "© 2026 TeacherAid",
  },
};
