// Imports the student-phone mockups from the Claude Design canvas into the website.
// The canvas is edited by hand, so re-run this after pulling fresh copies of its files:
//   node scripts/import-screens.mjs <folder holding the canvas's *.dc.html files>
// Each artboard becomes a static, non-interactive HTML fragment in components/site/screens.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SCREENS = {
  progress: "Progress",
  join: "Join",
  lobby: "Lobby",
  vote: "OpenerVote",
  reason: "OpenerReason",
  result: "OpenerResult",
  question: "Question",
  offline: "Offline",
  numeric: "Numeric",
  correct: "Correct",
  ask: "Ask",
};

const dir = process.argv[2];
if (!dir) {
  console.error("usage: node scripts/import-screens.mjs <canvas project folder>");
  process.exit(1);
}

function clean(src) {
  const start = src.indexOf("</helmet>");
  const end = src.lastIndexOf("</x-dc>");
  if (start < 0 || end < 0) throw new Error("not a .dc.html artboard");
  return (
    src
      .slice(start + "</helmet>".length, end)
      .trim()
      // Illustrations only: no links, controls or form fields.
      .replace(/<a href="[^"]*"/g, "<div")
      .replace(/<\/a>/g, "</div>")
      .replace(/<button(?: type="button")?/g, "<div")
      .replace(/<\/button>/g, "</div>")
      .replace(/<textarea([^>]*)style="/g, '<div$1style="white-space: pre-wrap; ')
      .replace(/<\/textarea>/g, "</div>")
      .replace(/<input([^>]*?)value="([^"]*)"([^>]*?)style="([^"]*)">/g, '<div style="$4">$2</div>')
      .replace(/<label/g, "<div")
      .replace(/<\/label>/g, "</div>")
      // No second document outline inside the page.
      .replace(/<(h[1-6]|section|nav|header|article)(?=[\s>])/g, "<div")
      .replace(/<\/(h[1-6]|section|nav|header|article)>/g, "</div>")
      .replace(/ (id|for|rows|maxlength|inputmode|role|aria-label|aria-current)="[^"]*"/g, "")
      // The site loads Golos Text under a hashed family name; inherit it.
      .replace(/font-family: 'Golos Text', system-ui, sans-serif/g, "font-family: inherit")
  );
}

const out = {};
for (const [key, file] of Object.entries(SCREENS)) {
  out[key] = clean(readFileSync(join(dir, `${file}.dc.html`), "utf8"));
}

const body =
  "// Generated by scripts/import-screens.mjs from the Claude Design canvas. Do not edit by hand.\n" +
  `export const SCREENS = ${JSON.stringify(out, null, 2)} as const;\n\n` +
  "export type ScreenName = keyof typeof SCREENS;\n";
writeFileSync(new URL("../components/site/screens.ts", import.meta.url), body);
console.log(`wrote ${Object.keys(out).length} screens`);
